name: 'NotionTEN'

on:
  schedule:
    - cron: '0 10,23 * * *'
  push:

jobs:
  NotionTEN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: pip install yagmail

      - name: NotionTEN
        run: python sendEmail.py
env:
  # Notion 相关
  DATABASEID: ${{ secrets.DATABASEID }}
  TOKEN: ${{ secrets.TOKEN }} 
  NOTION_DATE: ${{ secrets.NOTION_DATE }} 
  NOTION_STATUS: ${{ secrets.NOTION_STATUS }} 

  # 邮件服务相关
  SENDER: ${{ secrets.SENDER }} 
  RECEIVER: ${{ secrets.RECEIVER }} 
  SMTPSERVER: ${{ secrets.SMTPSERVER }} 
  PASSWORD: ${{ secrets.PASSWORD }} 
  PORT: ${{ secrets.PORT }} 